name: conditions-practise
on: [push]
jobs:
  raj-condition:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        if: github.ref == 'refs/heads/feature-*'
        run: echo "step 1 running"
      - name: step2
        if: github.ref == 'refs/heads/main'
        run: echo "step 2 running"
      - name: step2
        run: echo "step 2 running"
      - name: step3
        run: echo "step 3 running"