name: parallel

on: push

jobs:
  parallel-pipeline-1:
    runs-on: ubuntu-latest
    steps:
      - name: task1
        run: echo "I am from job 1"

  parallel-pipeline-2:
    # needs: parallel-pipeline-1
    runs-on: ubuntu-latest
    steps:
      - name: task2
        run: echo "I am from job 2"

  parallel-pipeline-3:
    needs: [parallel-pipeline-1, parallel-pipeline-2]
    runs-on: ubuntu-latest
    steps:
      - name: task3
        run: echo "I am from job 3"
